services:
  redpanda:
    image: redpandadata/redpanda:v24.2.4
    command:
      - redpanda start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --mode dev-container
    ports:
      - "19092:19092"
